"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[package]
disabled = true

[os]
symbols = { Debian = " \ue77d ", Ubuntu = " \ue73a ", Windows = " \uE62A " }

[directory]
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false
read_only = ""

[directory.substitutions]
"~/.config" = "\uf013"

[git_branch]
symbol = "\ue725 "

[git_status]
format = "[$all_status$ahead_behind]($style)"

untracked = '?$count '
modified = '~$count '
deleted = '-$count '
staged = '+$count '
stashed = '📦'

windows_starship = "/mnt/c/Program Files/starship/bin/starship.exe"

[cmd_duration]
min_time = 10
