"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

palette = "alan"

[palettes.alan]
pink = "#FA88AA"
red = "#FF5050"
cyan = "#87FAF0"
yellow = "#FAEB87"
violet = "#52154E"

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[package]
disabled = true

[os]
symbols = { Debian = " \ue77d ", Ubuntu = " \ue73a ", Windows = " \uE62A " }

[directory]
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false
read_only = ""

[directory.substitutions]
"/mnt/c" = "\uE62A"

[git_branch]
symbol = "\ue725 "
style = "bold pink"

[git_status]
format = "[$all_status$ahead_behind]($style)"

untracked = "?$count "
modified = "~$count "
renamed = "»$count "
deleted = "-$count "
staged = "+$count "

diverged = "⇕$count "
ahead = "⇡$count "
behind = "⇣$count "

stashed = "📦$count "

windows_starship = "/mnt/c/Program Files/starship/bin/starship.exe"

[cmd_duration]
min_time = 50
